<?php

namespace common\models;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "article".
 *
 * @property int $id
 * @property string|null $name
 * @property string|null $article_source
 * @property string|null $source_type
 * @property string|null $text
 * @property int|null $language_id
 *
 * @property Language $language
 * @property ArticleCategory[] $articleCategories
 * @property ArticleUser[] $articleUsers
 * @property DestinationArticle[] $destinationArticles
 * @property View[] $views
 */
class Article extends \yii\db\ActiveRecord
{
    public $category;

    public function init()
    {
        $category = ArrayHelper::getColumn(
            ArticleCategory::find()->where(['article_id' => \Yii::$app->request->get('id')])->all(),
            'category_id'
        );

        if (!empty($category)) {
            $this->category = $category;
        }
    }

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'article';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['text'], 'string'],
            [['language_id'], 'integer'],
            [['name', 'article_source', 'source_type'], 'string', 'max' => 255],
            [['language_id'], 'exist', 'skipOnError' => true, 'targetClass' => Language::className(), 'targetAttribute' => ['language_id' => 'id']],
            [['category'], 'safe']
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Заголовок',
            'article_source' => 'Источник статьи',
            'source_type' => 'Тип источника',
            'text' => 'Статья',
            'language_id' => 'Язык',
        ];
    }

    /**
     * Gets query for [[Language]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getLanguage()
    {
        return $this->hasOne(Language::className(), ['id' => 'language_id']);
    }

    /**
     * Gets query for [[ArticleCategories]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getArticleCategories()
    {
        return $this->hasMany(ArticleCategory::className(), ['article_id' => 'id']);
    }

    /**
     * Gets query for [[ArticleUsers]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getArticleUsers()
    {
        return $this->hasMany(ArticleUser::className(), ['article_id' => 'id']);
    }

    /**
     * Gets query for [[DestinationArticles]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getDestinationArticles()
    {
        return $this->hasMany(DestinationArticle::className(), ['article_id' => 'id']);
    }

    /**
     * Gets query for [[Views]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getViews()
    {
        return $this->hasMany(View::className(), ['article_id' => 'id']);
    }

    public static function getCategory($data)
    {
        $result = '';
        if($data->articleCategories) {
            foreach ($data->articleCategories as $value) {
                $category = Category::findOne($value->category_id);
                $result .= $category->name . ', ';
            }
        }
        $result = substr($result, 0, strlen($result)-2);
        return $result;
    }

    public function beforeSave($insert)
    {
        $language = Language::findOne(['language' => 'Русский']);
        $this->language_id = $language->id;
        $this->source_type = 'Добавлено вручную';
        $this->article_source = Yii::$app->user->identity->id;

        return parent::beforeSave($insert);
    }

    public function afterSave($insert, $changedAttributes)
    {
        $post = \Yii::$app->request->post('Article');

        if ($post['category']) {
            ArticleCategory::deleteAll(['article_id' => $this->id]);

            foreach ($post['category'] as $item) {
                $category = new ArticleCategory();
                $category->article_id = $this->id;
                $category->category_id = $item;

                $category->save();
            }
        }

        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
}
